# Data Analytics vs Data Science vs AI - Code Demo

This notebook is a simplified, illustrative demo designed to accompany the Data Analytics vs Data Science vs AI infographic.
It uses a minimal 4-month sales dataset to show how each discipline approaches the same data differently:

- **Data Analytics** - Summarising what happened (descriptive)
- **Data Science** - Predicting what might happen next (ML model)
- **AI** - Deciding what to do about it (rule-based and LLM-based)

Note: The models and methods here are intentionally basic and the LLM section is pseudocode-style illustration only.

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# A simple historical dataset
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr'],
    'Sales': [100, 150, 180, 220]
}

df = pd.DataFrame(data)
display(df)

  Month  Sales
0   Jan    100
1   Feb    150
2   Mar    180
3   Apr    220

In [2]:
# ---------------------------------------
# 1. DATA ANALYTICS
# ---------------------------------------

print("=== Data Analytics: What happened? ===")
display(df)

# Calculate month-over-month growth rate
df['Growth Rate'] = df['Sales'].pct_change()
print("\nMonth-over-month growth rate:")

display(df)

=== Data Analytics: What happened? ===

  Month  Sales
0   Jan    100
1   Feb    150
2   Mar    180
3   Apr    220

Month-over-month growth rate:

  Month  Sales  Growth Rate
0   Jan    100          NaN
1   Feb    150     0.500000
2   Mar    180     0.200000
3   Apr    220     0.222222

In [3]:
# ---------------------------------------
# 2. DATA SCIENCE
# ---------------------------------------
print("\n=== Data Science: What is likely to happen next? ===")

# Convert month names into simple numbers for the model
# Jan = 1, Feb = 2, Mar = 3, Apr = 4
df['MonthNumber'] = [1, 2, 3, 4]

# Input feature: MonthNumber
X = df[['MonthNumber']]

# Target value: Sales
y = df['Sales']

# Train a simple machine learning model
model = LinearRegression()
model.fit(X, y)

# Predict sales for May
may_month_number = pd.DataFrame({'MonthNumber': [5]})
predicted_sales_may = model.predict(may_month_number)[0]

print(f"Predicted sales for May: ${predicted_sales_may:.2f}")

=== Data Science: What is likely to happen next? ===
Predicted sales for May: $260.00

In [4]:
# ---------------------------------------
# 3. AI
# ---------------------------------------

print("\n=== AI: What should we do about it? ===")

# Simple rule-based AI decision
if predicted_sales_may >= 250:
    recommendation = "Sales are expected to be strong. Prepare more inventory and increase marketing."
elif predicted_sales_may >= 200:
    recommendation = "Sales are healthy. Continue current sales strategy and monitor performance."
else:
    recommendation = "Sales may be weak. Investigate customer demand and consider a promotion."

print(f"AI Recommendation: {recommendation}")

=== AI: What should we do about it? ===
AI Recommendation: Sales are expected to be strong. Prepare more inventory and increase marketing.

In [ ]:
# ---------------------------------------
# 4. Or using AI - LLM-based recommendation
# ---------------------------------------

print("\n=== AI: Interpret the data and recommend action ===")

# This is the information we will pass to the AI model
crm_summary = f"""
We are analyzing a simple CRM sales dataset.

Historical sales:
{df[['Month', 'Sales', 'Growth Rate']].to_string(index=False)}

The data science model predicts May sales to be {predicted_sales_may:.2f}.

Please explain:

1. What the sales trend means.
2. What action the sales team should take.
3. Any risk or caution to consider.

Keep the answer short and practical.
"""

print(crm_summary)

In [ ]:
from openai import OpenAI

client = OpenAI()

response = client.responses.create(
    model="gpt-5.5",
    input=crm_summary
)

print(response.output_text)